Repository neulsom-EZY/EZY-client, pull requests merged in 2021-10, with the labels that each got.

#59 Feature/section 4
  src/App.js
  src/Components/Section1/style.js
  src/Components/Section4/Section4.js
  src/Components/Section4/style.js
  src/fonts/AppleSDGothicNeoB.eot
  src/fonts/AppleSDGothicNeoB.ttf
  src/fonts/AppleSDGothicNeoB.woff
  src/fonts/AppleSDGothicNeoB.woff2
  src/fonts/AppleSDGothicNeoL.eot
  src/fonts/AppleSDGothicNeoL.ttf
  src/fonts/AppleSDGothicNeoL.woff
  src/fonts/AppleSDGothicNeoL.woff2
  src/fonts/AppleSDGothicNeoR.eot
  src/fonts/AppleSDGothicNeoR.ttf
  src/fonts/AppleSDGothicNeoR.woff
  src/fonts/AppleSDGothicNeoR.woff2
  src/fonts/AppleSDGothicNeoSB.eot
  src/fonts/AppleSDGothicNeoSB.ttf
  src/fonts/AppleSDGothicNeoSB.woff
  src/fonts/AppleSDGothicNeoSB.woff2
  src/fonts/AppleSDGothicNeoT.eot
  src/fonts/AppleSDGothicNeoT.ttf
  src/fonts/AppleSDGothicNeoT.woff
  src/fonts/AppleSDGothicNeoT.woff2
  src/fonts/Font.js
  src/fonts/LICENSE_OFL.txt
  src/fonts/NotoSansKR-Black.otf
  src/fonts/NotoSansKR-Black.woff
  src/fonts/NotoSansKR-Black.woff2
  src/fonts/NotoSansKR-Bold.otf
  src/fonts/NotoSansKR-Bold.woff
  src/fonts/NotoSansKR-Bold.woff2
  src/fonts/NotoSansKR-DemiLight.otf
  src/fonts/NotoSansKR-DemiLight.woff
  src/fonts/NotoSansKR-DemiLight.woff2
  src/fonts/NotoSansKR-Light.otf
  src/fonts/NotoSansKR-Light.woff
  src/fonts/NotoSansKR-Light.woff2
  src/fonts/NotoSansKR-Medium.otf
  src/fonts/NotoSansKR-Medium.woff
  src/fonts/NotoSansKR-Medium.woff2
  src/fonts/NotoSansKR-Regular.otf
  src/fonts/NotoSansKR-Regular.woff
  src/fonts/NotoSansKR-Regular.woff2
  src/fonts/NotoSansKR-Thin.otf
  src/fonts/NotoSansKR-Thin.woff
  src/fonts/NotoSansKR-Thin.woff2
Labels: completed page

#60 [Complete]Feature/section 4
  src/App.js
  src/Assets/Section4/Bottom.png
  src/Assets/Section4/Top.png
  src/Components/Section1/style.js
  src/Components/Section2/Section2.js
  src/Components/Section3/Section3.js
  src/Components/Section3/style.js
  src/Components/Section4/Section4.js
  src/Components/Section4/style.js
  src/Components/index.js
  src/Hooks/Fadeout.js
  src/fonts/AppleSDGothicNeoB.eot
  src/fonts/AppleSDGothicNeoB.ttf
  src/fonts/AppleSDGothicNeoB.woff
  src/fonts/AppleSDGothicNeoB.woff2
  src/fonts/AppleSDGothicNeoL.eot
  src/fonts/AppleSDGothicNeoL.ttf
  src/fonts/AppleSDGothicNeoL.woff
  src/fonts/AppleSDGothicNeoL.woff2
  src/fonts/AppleSDGothicNeoR.eot
  src/fonts/AppleSDGothicNeoR.ttf
  src/fonts/AppleSDGothicNeoR.woff
  src/fonts/AppleSDGothicNeoR.woff2
  src/fonts/AppleSDGothicNeoSB.eot
  src/fonts/AppleSDGothicNeoSB.ttf
  src/fonts/AppleSDGothicNeoSB.woff
  src/fonts/AppleSDGothicNeoSB.woff2
  src/fonts/AppleSDGothicNeoT.eot
  src/fonts/AppleSDGothicNeoT.ttf
  src/fonts/AppleSDGothicNeoT.woff
  src/fonts/AppleSDGothicNeoT.woff2
  src/fonts/Font.js
  src/fonts/LICENSE_OFL.txt
  src/fonts/NotoSansKR-Black.otf
  src/fonts/NotoSansKR-Black.woff
  src/fonts/NotoSansKR-Black.woff2
  src/fonts/NotoSansKR-Bold.otf
  src/fonts/NotoSansKR-Bold.woff
  src/fonts/NotoSansKR-Bold.woff2
  src/fonts/NotoSansKR-DemiLight.otf
  src/fonts/NotoSansKR-DemiLight.woff
  src/fonts/NotoSansKR-DemiLight.woff2
  src/fonts/NotoSansKR-Light.otf
  src/fonts/NotoSansKR-Light.woff
  src/fonts/NotoSansKR-Light.woff2
  src/fonts/NotoSansKR-Medium.otf
  src/fonts/NotoSansKR-Medium.woff
  src/fonts/NotoSansKR-Medium.woff2
  src/fonts/NotoSansKR-Regular.otf
  src/fonts/NotoSansKR-Regular.woff
  src/fonts/NotoSansKR-Regular.woff2
  src/fonts/NotoSansKR-Thin.otf
  src/fonts/NotoSansKR-Thin.woff
  src/fonts/NotoSansKR-Thin.woff2
Labels: completed page

#61 [Fix] Section2 X-scroll issue
  src/Components/Section2/Section2.js
Labels: bug, kill an Bug, receive comments

#68 [UPDATE] Monitoring Script, Meta Tag
  public/index.html
Labels: enhancement, receive comments

#82 Feature/section 6
  src/App.js
  src/Assets/Section6/Hand.png
  src/Assets/Section6/Phone.png
  src/Components/Section6/Section6.js
  src/Components/Section6/style.js
  src/Components/index.js
Labels: bug, enhancement

#83 Footer 수정
  src/App.js
  src/Assets/Section6/Hand.png
  src/Assets/Section6/Phone.png
  src/Components/Section6/Section6.js
  src/Components/Section6/style.js
  src/Components/Section7/style.js
  src/Components/index.js
Labels: enhancement
